language: python
sudo: false
cache: pip

python:
  - "2.7"

addons:
  postgresql: "9.2" # minimal postgresql version for the daterange method
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

env:
  global:
  - VERSION="9.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  # - TRANSIFEX_USER='transbot@odoo-community.org'

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="auth_supplier,mail_environment,server_environment,server_env_base_external_referentials"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/vauxoo/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - printf '[options]\n\nrunning_env = dev\n' > ${HOME}/.openerp_serverrc
  - ln -s ${TRAVIS_BUILD_DIR}/server_environment_files_sample ${TRAVIS_BUILD_DIR}/server_environment_files
script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
